// <auto-generated />
using System;
using ApiForIonic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiForIonic.Migrations
{
    [DbContext(typeof(IonicAppDbContext))]
    [Migration("20191210070316_PaymentHistory")]
    partial class PaymentHistory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiForIonic.Models.CreditUnion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CreditUnions");
                });

            modelBuilder.Entity("ApiForIonic.Models.PaymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<long>("CreditUnionId");

                    b.Property<DateTime>("PaymentMadeOn");

                    b.HasKey("Id");

                    b.HasIndex("CreditUnionId");

                    b.ToTable("PaymentHistories");
                });

            modelBuilder.Entity("ApiForIonic.Models.PaymentHistory", b =>
                {
                    b.HasOne("ApiForIonic.Models.CreditUnion", "CreditUnion")
                        .WithMany()
                        .HasForeignKey("CreditUnionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
